services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: weather-api
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - weather-net

  frontend:
    image: nginx:alpine
    container_name: weather-ui
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge